USE social_network;
CREATE TABLE tbl_role (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  des VARCHAR(255) NOT NULL,
  roleName VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL
);
CREATE TABLE tbl_user (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL UNIQUE,
  adress VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password1 VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  dateOfBirth TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  role_id INT NOT NULL,
  status1 INT NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_user_role_id FOREIGN KEY (role_id) REFERENCES tbl_role(id)
);
CREATE TABLE tbl_post (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  content TEXT NOT NULL,
  user_id INT NOT NULL,
  status1 VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_post_user_id FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);

CREATE TABLE tbl_comment (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  post_id INT NOT NULL,
  user_id INT NOT NULL,
  content  TEXT NOT NULL,
  status1 VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_comment_post_id FOREIGN KEY (post_id) REFERENCES tbl_post(id),
  CONSTRAINT fk_comment_user_id FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);

CREATE TABLE tbl_image (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  status1 VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL
);
CREATE TABLE tbl_images_comments_posts (
  model_Type varchar(255) NOT NULL,
  model_Id INT NOT NUL , 
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_images_comments_posts_model_Id FOREIGN KEY (model_Id) REFERENCES tbl_post(id),
  CONSTRAINT fk_images_comments_posts_model_Id2 FOREIGN KEY (model_Id) REFERENCES tbl_comment(id)
);

CREATE TABLE tbl_like (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  status1 VARCHAR(255) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_like_user_id FOREIGN KEY (user_id) REFERENCES tbl_user(id)
);

CREATE TABLE tbl_likes_comments_posts (
  model_Type varchar(255) NOT NULL,
  model_Id INT NOT NULL,
  likes_id INT NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_likes_comments_posts_model_Id FOREIGN KEY (model_Id) REFERENCES tbl_post(id) ON DELETE CASCADE,
  CONSTRAINT fk_likes_comments_posts_model_Id2 FOREIGN KEY (model_Id) REFERENCES tbl_comment(id) ON DELETE CASCADE,
  CONSTRAINT fk_likes_comments_posts_likes_id FOREIGN KEY (likes_id) REFERENCES tbl_like(id)
);
CREATE TABLE tbl_relationship (
   id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
   relationshipName varchar(255) DEFAULT NULL,
   sender_id int(11) NOT NULL,
   receiver_id int(11) NOT NULL,
   status varchar(255) NOT NULL,
   created_at timestamp NOT NULL DEFAULT current_timestamp(),
   updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
   deleted_at timestamp NULL DEFAULT NULL,
   CONSTRAINT fk_relationship_sender_id FOREIGN KEY (sender_id) REFERENCES tbl_user(id),
   CONSTRAINT fk_relationship_receiver_id FOREIGN KEY (receiver_id) REFERENCES tbl_user(id)
);
CREATE TABLE tbl_boxChat (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name varchar(255) NOT NULL,
  avatar varchar(255) DEFAULT NULL,
  status varchar(255) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE tbl_user_boxChat (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  boxChat_id INT NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_user_boxChat_user_id FOREIGN KEY (user_id) REFERENCES tbl_user(id),
  CONSTRAINT fk_user_boxChat_boxChat_id FOREIGN KEY (boxChat_id) REFERENCES tbl_boxChat(id)
);

CREATE TABLE tbl_chat (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  boxChat_id INT NOT NULL,
  content text DEFAULT NULL,
  status varchar(255) DEFAULT NULL,
  images varchar(255) DEFAULT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_chat_user_id FOREIGN KEY (user_id) REFERENCES tbl_user(id),
  CONSTRAINT fk_chat_boxChat_id FOREIGN KEY (boxChat_id) REFERENCES tbl_boxChat(id)
);